# Generated by Django 2.0.4 on 2018-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='questionnaire',
        ),
        migrations.AddField(
            model_name='question',
            name='questionType',
            field=models.CharField(default='integer', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
