# Generated by Django 2.0.4 on 2018-04-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20180430_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostQuestionnaire',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='title',
        ),
        migrations.AddField(
            model_name='participant',
            name='ability',
            field=models.CharField(choices=[('0', 'Beginner'), ('1', 'Intermediate'), ('2', 'Advanced'), ('3', 'Professional')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='participant',
            name='hours_listening_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='hours_practiced_per_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participant',
            name='instrument_list',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='participant',
            name='plays_instruments',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default=None, max_length=3),
        ),
        migrations.AddField(
            model_name='participant',
            name='predicted_playing_time',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='preferred_genres',
            field=models.CharField(default='', max_length=500),
        ),
    ]
