# Generated by Django 2.0.4 on 2018-04-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_auto_20180430_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ability',
            field=models.CharField(choices=[('0', 'Beginner'), ('1', 'Intermediate'), ('2', 'Advanced'), ('3', 'Professional')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='o', max_length=6),
        ),
        migrations.AlterField(
            model_name='participant',
            name='plays_instruments',
            field=models.CharField(choices=[('y', 'yes'), ('n', 'no')], default='', max_length=3),
        ),
    ]
