# Generated by Django 2.0.4 on 2018-04-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20180430_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='first_system_estimated_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
