# Generated by Django 2.0.4 on 2018-05-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_auto_20180430_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteName', models.CharField(max_length=3)),
                ('startTime', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_system_play_again',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='participant',
            name='plays_instruments',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='participant',
            name='second_system_play_again',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='', max_length=3),
        ),
    ]
