# Generated by Django 2.0.4 on 2018-05-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_auto_20180513_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='participant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='study.Participant'),
        ),
        migrations.AlterField(
            model_name='note',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='noteName',
            field=models.CharField(default='000', max_length=3),
        ),
        migrations.AlterField(
            model_name='note',
            name='startTime',
            field=models.IntegerField(default=0),
        ),
    ]
