# Generated by Django 2.0.4 on 2018-05-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_auto_20180513_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='interaction',
            field=models.CharField(default='echo', max_length=10),
        ),
    ]
