# Generated by Django 2.0.4 on 2018-05-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0014_computernote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ability',
            field=models.CharField(blank=True, choices=[('0', 'Beginner'), ('1', 'Intermediate'), ('2', 'Advanced'), ('3', 'Professional')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hours_practiced_per_week',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='instrument_list',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
