# Generated by Django 2.0.4 on 2018-05-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0015_auto_20180515_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='ability',
            field=models.CharField(blank=True, choices=[(None, 'Not applicable'), ('0', 'Beginner'), ('1', 'Intermediate'), ('2', 'Advanced'), ('3', 'Professional')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hours_practiced_per_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
