# Generated by Django 2.0.4 on 2018-06-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0016_auto_20180515_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='select_three',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default='o', max_length=6),
        ),
    ]
