# Generated by Django 2.0.4 on 2018-06-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0017_participant_select_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='filter_q_1',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='participant',
            name='filter_q_2',
            field=models.CharField(choices=[('1', '1 (option 1)'), ('2', '2 (option 2)'), ('3', '3 (option 3)'), ('4', '4 (option 4)'), ('5', '5 (option 5)')], default='o', max_length=20),
        ),
    ]
