# Generated by Django 2.0.4 on 2018-07-30 14:14

import django.core.validators
from django.db import migrations, models
import study.models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0018_auto_20180629_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=0, error_messages={'max_value': 'You must enter a valid age in years.', 'min_value': 'You must be over 18 years of age to participate in this study.'}, validators=[django.core.validators.MaxValueValidator(112), django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='filter_q_1',
            field=models.CharField(default='', max_length=20, validators=[study.models.says_music]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='filter_q_2',
            field=models.CharField(choices=[('1', '1 (option 1)'), ('2', '2 (option 2)'), ('3', '3 (option 3)'), ('4', '4 (option 4)'), ('5', '5 (option 5)')], default='o', max_length=20, validators=[study.models.is_four]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.CharField(choices=[('P', 'Please choose'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='o', max_length=6),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hours_listening_per_week',
            field=models.IntegerField(error_messages={'max_value': 'You have entered more hours than there are in a week.', 'min_value': 'This field cannot be negative.'}, validators=[django.core.validators.MaxValueValidator(168), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='hours_practiced_per_week',
            field=models.IntegerField(blank=True, error_messages={'max_value': 'You have entered more hours than there are in a week.', 'min_value': 'This field cannot be negative.'}, null=True, validators=[django.core.validators.MaxValueValidator(168), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='predicted_playing_time',
            field=models.CharField(default='', max_length=100, validators=[study.models.valid_time]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='select_three',
            field=models.CharField(choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four')], default='o', max_length=6, validators=[study.models.is_three]),
        ),
    ]
